-- HuyVo Portfolio V1.2.0 — Media & Project Assets
-- Run this in Supabase SQL Editor before using Save live, Media assets and Analytics in /admin.

create table if not exists public.portfolio_profiles (
  id text primary key,
  data jsonb not null,
  updated_at timestamptz not null default now()
);

alter table public.portfolio_profiles enable row level security;

drop policy if exists "portfolio_profiles_public_read" on public.portfolio_profiles;
create policy "portfolio_profiles_public_read"
  on public.portfolio_profiles
  for select
  using (true);

-- Media fields are stored inside portfolio_profiles.data JSONB; no extra media table is required for URL-based assets.
-- No insert/update policy is created for anon users on portfolio_profiles.
-- Writes are performed only through the Next.js API route using SUPABASE_SERVICE_ROLE_KEY.

create table if not exists public.portfolio_events (
  id bigint generated by default as identity primary key,
  event_type text not null,
  path text,
  label text,
  target text,
  referrer text,
  user_agent text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists portfolio_events_created_at_idx
  on public.portfolio_events (created_at desc);

create index if not exists portfolio_events_event_type_idx
  on public.portfolio_events (event_type);

create index if not exists portfolio_events_path_idx
  on public.portfolio_events (path);

alter table public.portfolio_events enable row level security;

-- Analytics writes and reads are handled by server routes with SUPABASE_SERVICE_ROLE_KEY.
-- No public select policy is created, so visitor analytics stays private inside /admin.
